FROM kabanero/ubi8-maven:0.3.1

USER root

RUN  groupadd --gid 1000 java_group \
  && useradd --uid 1000 --gid java_group --shell /bin/bash --create-home java_user \
  && mkdir -p /mvn/repository \
  && chown -R java_user:java_group /mvn \
  && mkdir -p /opt/ol \
  && chown -R java_user:java_group /opt


COPY ./LICENSE /licenses/
COPY --chown=java_user:java_group ./project /project
COPY --chown=java_user:java_group ./config /config

RUN  /project/util/check_version build

WORKDIR /project/

RUN mkdir -p /mvn/repository
RUN mvn -B -Dmaven.repo.local=/mvn/repository -N io.takari:maven:wrapper -Dmaven=$(mvn help:evaluate -Dexpression=maven.version -q -DforceStdout)
RUN mvn -B -Pstack-image-package -Dmaven.repo.local=/mvn/repository liberty:install-server liberty:create install dependency:go-offline
RUN chmod -R 777 /opt/ol


WORKDIR /project/user-app

USER java_user

ENV APPSODY_MOUNTS="~/.m2/repository:/mvn/repository;.:/project/user-app"

ENV APPSODY_USER_RUN_AS_LOCAL=true

# Allow validate to distinguish build via APPSODY_DEV_MODE
ENV APPSODY_PREP="export APPSODY_DEV_MODE=prep;  ../validate.sh"

ENV APPSODY_RUN="export APPSODY_DEV_MODE=run; mvn -B -Pstack-image-run -DappsDirectory=apps -Dmaven.repo.local=/mvn/repository pre-integration-test liberty:dev"

ENV APPSODY_DEBUG="export APPSODY_DEV_MODE=debug; mvn -B -Pstack-image-run -DappsDirectory=apps -Dmaven.repo.local=/mvn/repository pre-integration-test liberty:dev"

# Keep liberty:create before 'package' phase to be consistent with "Dockerfile" for 'appsody build'
ENV APPSODY_TEST="export APPSODY_DEV_MODE=test; exec mvn -B -Pstack-image-run -DappsDirectory=apps -Dmaven.repo.local=/mvn/repository clean liberty:create pre-integration-test liberty:install-feature liberty:start liberty:deploy failsafe:integration-test liberty:stop failsafe:verify"

ENV PORT=9080

EXPOSE 9080
EXPOSE 9443
EXPOSE 7777
